### ISSUE TITLE
Problem with codebox template

### ISSUE THREAD

**Issue by vanniand** [justinhunt/moodle-filter_generico#32]
Hi, thnx for this plugin and thnx for the default bundles.
I'm trying to use the codebox bundle with the new release of highlight 11.6.0, but I'm facing a problem.
It seems the bundle is not compatile with this new release any more.
I tried to modify the configuration but I always got this error:

require.min.js:5 Uncaught Error: No define call for http://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/highlight.min.js
http://requirejs.org/docs/errors.html#nodefine
    at makeError (require.min.js:5:1067)
    at Object.completeLoad (require.min.js:5:12223)
    at HTMLScriptElement.onScriptLoad (require.min.js:5:13016)

I put in Custom JS
hljs.highlightAll()

Any idea to resolve it?

Thanks 
Andrea

**Comment by justinhunt** [comment]
Hi Andrea

I had a look at it. I think Highlight JS has moved on from Require JS and if you want to use the newest version, you need to "shim" this just applies a name to the exported module (highlightjs). It says the function highlight block will be deprecated in version 12.0 too. 

I attached the slightly modified template bundle with the shim. Please try it out
[codebox.txt](https://github.com/justinhunt/moodle-filter_generico/files/9604352/codebox.txt)

**Comment by vanniand** [comment]
Hi Justin,
you are right, the problem was there. THNX
I just modified your new template bundle as follow:
$('#' + @@AUTOID@@).each(function(i, block) {
hljs.highlightElement(block);
  $(block).bind('copy paste cut', function (e) {
       if(@@allow_copy@@=='false'){
           e.preventDefault(); //disable cut,copy,paste
           return false;
      }
    });
});

because  hljs.highlightBlock(block); is deprecated.

Thnx again

**Comment by justinhunt** [comment]
Got it.  I will update it with your code. Thanks.
