### ISSUE TITLE
Generico: Tabs and Accordian block sidebar on the left

### ISSUE THREAD

**Issue by mattgig** [justinhunt/moodle-filter_generico#33]
The templates for tabs and accordian block the opening and the closing of the sidebar in Moodle 4.0.5 (maybe in earlier versions too) because of an error in the console.

![image](https://user-images.githubusercontent.com/7272764/202302096-f6db1bb2-d6b7-4774-bf58-93dd263aac26.png)

Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'hide'
    at Function.error (/lib/javascript.php/1667526124/lib/jquery/jquery-3.6.0.min.js:2:2616)
    at HTMLButtonElement.<anonymous> (jquery-ui.min.js:6:5615)
    at Function.each (/lib/javascript.php/1667526124/lib/jquery/jquery-3.6.0.min.js:2:3003)
    at S.fn.init.each (/lib/javascript.php/1667526124/lib/jquery/jquery-3.6.0.min.js:2:1481)
    at t.fn.<computed> [as tooltip] (jquery-ui.min.js:6:5357)
    at Drawers.closeDrawer (/lib/requirejs.php/1667526124/core/first.js:4539:7123)
    at HTMLDocument.<anonymous> (/lib/requirejs.php/1667526124/core/first.js:4539:9935)

For a demonstration see: https://demo.poodll.com/mod/page/view.php?id=140

**Comment by justinhunt** [comment]
Hi Matthias, this is a known issue unfortunately. 

In Moodle 4.0 they broke jquery-ui compatibility , so that if we load it, then the nav drawer breaks. I removed jquery-ui from everywhere I could. But I did not have a replacement solution for tabs and accordians.

I will try and do a new implementation soon.

**Comment by danmarsden** [comment]
Hey Justin! - hope you're keeping well! - Alex put together something quickly for one of our clients here to get those working in a 4.1 site here:
https://github.com/justinhunt/moodle-filter_generico/compare/master...alexmorrisnz:moodle-filter_generico:accordion-fix

might be useful at some point.

**Comment by justinhunt** [comment]
Cor, thats good stuff! Thanks @danmarsden and @alexmorrisnz

**Comment by justinhunt** [comment]
This should be fixed now. Thanks for reporting it @mattgig and fixing it @alexmorrisnz
